drop database if exists GYM;
create database GYM;

use GYM;

/******************** TABLES **********************/

CREATE TABLE ARANCELES
(
  AEROBICO FLOAT,
  AEROBICO3 FLOAT,
  FITYOGA FLOAT,
  AEROBICOUNIV FLOAT,
  AEROBICOINF FLOAT,
  SPINNING FLOAT,
  PILATES FLOAT,
  PILATES3 FLOAT,
  MUSCULACION FLOAT,
  MUSCULACIONC FLOAT,
  MUSCULACIONU FLOAT,
  COMBO1 FLOAT,
  COMBO2 FLOAT,
  COMBO3 FLOAT,
  COMBO4 FLOAT,
  COMBO5 FLOAT,
  COMBO6 FLOAT,
  ID_ARANCELES CHAR(1) NOT NULL
);
CREATE TABLE ASISTENCIA
(
  ID_ASISTENCIA INTEGER NOT NULL,
  ID_DATOS_PERS INTEGER NOT NULL,
  FECHA DATE,
  ACTIV INTEGER,
  CONSTRAINT INTEG_33 PRIMARY KEY (ID_ASISTENCIA)
);
CREATE TABLE CLASE
(
  ID_CLASE INTEGER NOT NULL,
  ID_PROFES INTEGER NOT NULL,
  FECHA DATE,
  ACTIV BIGINT,
  CONSTRAINT INTEG_29 PRIMARY KEY (ID_CLASE)
);
CREATE TABLE DATOS_PERS
(
  ID_DATOS_PERS INTEGER NOT NULL,
  NOMBRE VARCHAR(20),
  APELLIDO VARCHAR(20),
  DNI VARCHAR(12),
  FECHA_NAC VARCHAR(10),
  FECHA_ING DATE,
  DIR VARCHAR(30),
  TEL VARCHAR(20),
  SEXO CHAR(1),
  OBSERV VARCHAR(3000),
  FECHA_ULT_PAGO DATE,
  ACTIV BIGINT,
  DEUDA FLOAT,
  MOROSO CHAR(1),
  CONSTRAINT INTEG_11 PRIMARY KEY (ID_DATOS_PERS)
);
CREATE TABLE FICHA_MEDICA
(
  ID_FICHA_MEDICA INTEGER NOT NULL,
  ID_DATOS_PERS INTEGER NOT NULL,
  TEL_EMERG VARCHAR(20),
  GRUPO_SANG VARCHAR(2),
  FACTOR VARCHAR(3),
  ALERGICO VARCHAR(30),
  MEDICAM VARCHAR(30),
  OBSERV VARCHAR(3000),
  PATOLOGIAS INTEGER,
  CONSTRAINT INTEG_13 PRIMARY KEY (ID_FICHA_MEDICA)
);
CREATE TABLE PAGOS
(
  ID_PAGOS INTEGER NOT NULL,
  ID_DATOS_PERS INTEGER NOT NULL,
  FECHA DATE,
  MONTO FLOAT,
  CONSTRAINT INTEG_25 PRIMARY KEY (ID_PAGOS)
);
CREATE TABLE PROFES
(
  ID_PROFES INTEGER NOT NULL,
  NOMBRE VARCHAR(20),
  APELLIDO VARCHAR(20),
  DNI VARCHAR(12),
  FECHA_NAC DATE,
  DIR VARCHAR(30),
  TEL VARCHAR(20),
  SEXO CHAR(1),
  OBSERV VARCHAR(3000),
  CONSTRAINT INTEG_27 PRIMARY KEY (ID_PROFES)
);
CREATE TABLE USUARIOS
(
  USUARIO VARCHAR(20),
  PASSWD VARCHAR(20),
  ADMINIS CHAR(1)
);
/********************* VIEWS **********************/

/******************* EXCEPTIONS *******************/

/******************** TRIGGERS ********************/



ALTER TABLE ASISTENCIA ADD CONSTRAINT FK_ASISTENCIA
  FOREIGN KEY (ID_DATOS_PERS) REFERENCES DATOS_PERS (ID_DATOS_PERS);
ALTER TABLE CLASE ADD CONSTRAINT FK_CLASE
  FOREIGN KEY (ID_PROFES) REFERENCES PROFES (ID_PROFES) ON DELETE CASCADE;
ALTER TABLE FICHA_MEDICA ADD CONSTRAINT FK_FICHA_MEDICA
  FOREIGN KEY (ID_DATOS_PERS) REFERENCES DATOS_PERS (ID_DATOS_PERS) ON DELETE CASCADE;
ALTER TABLE PAGOS ADD CONSTRAINT FK_PAGOS
  FOREIGN KEY (ID_DATOS_PERS) REFERENCES DATOS_PERS (ID_DATOS_PERS) ON DELETE CASCADE;
ALTER TABLE `GYM`.`ASISTENCIA` CHANGE COLUMN `ID_ASISTENCIA` `ID_ASISTENCIA` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `GYM`.`CLASE` CHANGE COLUMN `ID_CLASE` `ID_CLASE` INT(11) NOT NULL AUTO_INCREMENT  ;
ALTER TABLE `GYM`.`DATOS_PERS` CHANGE COLUMN `ID_DATOS_PERS` `ID_DATOS_PERS` INT(11) NOT NULL AUTO_INCREMENT  ;
ALTER TABLE `GYM`.`FICHA_MEDICA` CHANGE COLUMN `ID_FICHA_MEDICA` `ID_FICHA_MEDICA` INT(11) NOT NULL AUTO_INCREMENT  ;
ALTER TABLE `GYM`.`PAGOS` CHANGE COLUMN `ID_PAGOS` `ID_PAGOS` INT(11) NOT NULL AUTO_INCREMENT  ;
ALTER TABLE `GYM`.`PROFES` CHANGE COLUMN `ID_PROFES` `ID_PROFES` INT(11) NOT NULL AUTO_INCREMENT  ;




