/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author alan
 */
public class AplicacionGUI extends javax.swing.JFrame {

    private PanelClientes panelClientes;
    private PanelActividades panelActividades;
    private AcercaDe acercaDe;
    public AplicacionGUI() {
        initComponents();
        panelClientes = new PanelClientes();
        panelActividades = new PanelActividades();
        acercaDe = new AcercaDe();
        tab.add("Clientes", panelClientes);
        tab.add("Actividades/Promociones", panelActividades);
        tab.add("Acerca de", acercaDe);
    }

    public PanelClientes getPanelClientes() {
        return panelClientes;
    }

    public PanelActividades getPanelActividades() {
        return panelActividades;
    }

    public JButton getBotDesconectar() {
        return BotDesconectar;
    }

    public JLabel getLabelUsuarioConect() {
        return LabelUsuarioConect;
    }
    
    
    public void setActionListener(ActionListener lis){
        BotDesconectar.addActionListener(lis);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        LabelUsuarioConect = new javax.swing.JLabel();
        BotDesconectar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion gimnacio Costa Norte");

        jLabel1.setText("Usuario conectado: ");

        LabelUsuarioConect.setText("NombreUsuario");

        BotDesconectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cross.png"))); // NOI18N
        BotDesconectar.setText("Desconectar");
        BotDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotDesconectarActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelUsuarioConect)
                .addGap(18, 18, 18)
                .addComponent(BotDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LabelUsuarioConect)
                    .addComponent(BotDesconectar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotDesconectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotDesconectarActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotDesconectar;
    private javax.swing.JLabel LabelUsuarioConect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
