/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Modelos.Arancel;
import Modelos.Combo;
import Modelos.Socioarancel;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import org.javalite.activejdbc.LazyList;
import org.javalite.activejdbc.Model;

/**
 *
 * @author Nico
 */
public class asistenciaCombo extends javax.swing.JDialog {

    /**
     * Creates new form asistenciaCombo
     */
    
    public int asiste;
    public asistenciaCombo(java.awt.Frame parent, boolean modal, Object id) {
        super(parent, modal);
        initComponents();
        DefaultTableModel defaultTable= (DefaultTableModel) tablaActCombo.getModel();
        defaultTable.setRowCount(0);
        LazyList<Socioarancel> socioArancel= Socioarancel.where("id_socio = ?", id);
        Iterator<Socioarancel> it= socioArancel.iterator();
        Arancel aran = null;
        while(it.hasNext()){
            Socioarancel socAr=it.next();
            aran= Arancel.findFirst("id = ? and categoria = ?", socAr.get("id_arancel"),"COMBO");
        }
        if(aran!=null){
            LazyList<Combo> comboAct=Combo.where("id_combo = ?", aran.get("id"));
            Iterator<Combo> itCombo= comboAct.iterator();
            while(itCombo.hasNext()){
                Combo combo= itCombo.next();
                aran=Arancel.findFirst("id = ?", combo.get("id_activ"));
                                        Object row[] = new Object[3];
                        row[0] = combo.getInteger("id_activ");
                        row[1] = aran.getString("nombre");
                        row[2] = false;
                        defaultTable.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tablaActCombo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaActCombo.setAutoCreateRowSorter(true);
        tablaActCombo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Actividad", "Asiste"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaActCombo.setColumnSelectionAllowed(true);
        tablaActCombo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tablaActCombo);
        tablaActCombo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int rows= tablaActCombo.getRowCount();
        boolean fin= false;
        for(int i=0; i<rows && !fin;i++){
            if(tablaActCombo.getValueAt(i, 2).equals(true)){
                fin=true;
                asiste= (Integer)tablaActCombo.getValueAt(i, 0);
            }
        }
        if(fin){
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaActCombo;
    // End of variables declaration//GEN-END:variables
}
