package Interfaces;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Component;
import java.awt.Desktop;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JViewport;
import org.edisoncor.gui.panel.PanelImage;


/**
 *
 * @author Nico
 */
public class IngresoGui extends javax.swing.JFrame {

    

    /**
     * Creates new form IngresoGui
     */
    public IngresoGui() throws Exception {
        initComponents();
        /* Component[] array=panelAsistencia.getComponents();
         for(int i=0;i<array.length;i++){
         ((JLabel)array[i]).setText("12/12/2012 "+i);
         }*/
       // Iniciar();
        //start();
    }
        
    public void limpiar(){
        nombre.setText("");
        fechaUltPago.setText("");
        fechaVence.setText("");
        cantDias.setText("");
        Component[] array=panelAsistencia.getComponents();
        for (Component array1 : array) {
            ((JTextArea)((JViewport)((JScrollPane) array1).getComponent(0)).getView()).setText("") ;
        }
    }
    
    public void limpiarAsistencias(){
        Component[] array=panelAsistencia.getComponents();
        for (Component array1 : array) {
            ((JTextArea)((JViewport)((JScrollPane) array1).getComponent(0)).getView()).setText("") ;
        } 
    }
    
 public void cargarSonido(String nombre) throws Exception {
         File soundFile = new File(getClass().getResource("/Sonidos/"+nombre).toURI());
         AudioInputStream soundIn = AudioSystem.getAudioInputStream(soundFile);
        AudioFormat format = soundIn.getFormat();
         DataLine.Info info = new DataLine.Info(Clip.class, format);

         Clip clip = (Clip)AudioSystem.getLine(info);
         clip.open(soundIn);
         //clip.start();
         clip.loop(1);
         {
        //    Thread.yield();
         }
            //clip.stop();

    }
 
 

    public void noIdentifado(){
        nombre.setText("?????");
        fechaUltPago.setText("?????");
        fechaVence.setText("?????");
        cantDias.setText("??");
        Component[] array=panelAsistencia.getComponents();
        for (Component array1 : array) {
            ((JLabel) array1).setText("");
        }
    }

    public JPanel getPanelAsistencia() {
        return panelAsistencia;
    }

    public JMenuItem getBusquedaManual() {
        return busquedaManual;
    }

    public JMenuItem getLimpiarVentana() {
        return limpiarVentana;
    }
    
    public void setActionListener(ActionListener lis){
        limpiarVentana.addActionListener(lis);
        busquedaManual.addActionListener(lis);
        darDeAlta.addActionListener(lis);
        gestAsis.addActionListener(lis);
    }

    public JMenuItem getGestAsis() {
        return gestAsis;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaUltPago = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fechaVence = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        cantDias = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoHuella = new javax.swing.JTextArea();
        imHuella = new org.edisoncor.gui.panel.PanelImage();
        jPanel4 = new javax.swing.JPanel();
        panelAsistencia = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea17 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextArea18 = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea19 = new javax.swing.JTextArea();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextArea20 = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextArea21 = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextArea22 = new javax.swing.JTextArea();
        jScrollPane25 = new javax.swing.JScrollPane();
        jTextArea23 = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        jTextArea24 = new javax.swing.JTextArea();
        jScrollPane27 = new javax.swing.JScrollPane();
        jTextArea25 = new javax.swing.JTextArea();
        jScrollPane28 = new javax.swing.JScrollPane();
        jTextArea26 = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        jTextArea27 = new javax.swing.JTextArea();
        jScrollPane30 = new javax.swing.JScrollPane();
        jTextArea28 = new javax.swing.JTextArea();
        jScrollPane31 = new javax.swing.JScrollPane();
        jTextArea29 = new javax.swing.JTextArea();
        jScrollPane32 = new javax.swing.JScrollPane();
        jTextArea30 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        busquedaManual = new javax.swing.JMenuItem();
        limpiarVentana = new javax.swing.JMenuItem();
        darDeAlta = new javax.swing.JMenuItem();
        gestAsis = new javax.swing.JMenuItem();

        setTitle("Ingreso de socios");
        setBackground(new java.awt.Color(236, 233, 216));
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(236, 233, 216));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del socio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century", 1, 14), java.awt.Color.black)); // NOI18N

        nombre.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        nombre.setForeground(new java.awt.Color(12, 134, 52));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("julito");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Fecha último pago:");

        fechaUltPago.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        fechaUltPago.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fechaUltPago.setText("12/11/12");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Fecha de vencimiento:");

        fechaVence.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        fechaVence.setForeground(new java.awt.Color(204, 0, 0));
        fechaVence.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fechaVence.setText("12/12/12");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel36.setText("Faltan");

        cantDias.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cantDias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantDias.setText("20");
        cantDias.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel38.setText("Días para el vencimiento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel36)
                .addGap(6, 6, 6)
                .addComponent(cantDias, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel38))
            .addComponent(nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaUltPago, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                        .addGap(147, 147, 147))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaVence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaUltPago)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6))
                    .addComponent(fechaVence))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantDias)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel38)))))
        );

        jPanel2.setBackground(new java.awt.Color(236, 233, 216));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Control de ingreso");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setMaximumSize(new java.awt.Dimension(340, 44));
        jLabel2.setMinimumSize(new java.awt.Dimension(340, 44));
        jLabel2.setPreferredSize(new java.awt.Dimension(340, 44));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Costa Norte logo-centro.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Costa Norte logo-centro.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        textoHuella.setEditable(false);
        textoHuella.setBackground(new java.awt.Color(236, 233, 216));
        textoHuella.setColumns(20);
        textoHuella.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        textoHuella.setForeground(new java.awt.Color(0, 153, 0));
        textoHuella.setRows(3);
        jScrollPane1.setViewportView(textoHuella);

        javax.swing.GroupLayout imHuellaLayout = new javax.swing.GroupLayout(imHuella);
        imHuella.setLayout(imHuellaLayout);
        imHuellaLayout.setHorizontalGroup(
            imHuellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        imHuellaLayout.setVerticalGroup(
            imHuellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel4.setLayout(new java.awt.BorderLayout());

        panelAsistencia.setBackground(new java.awt.Color(236, 233, 216));
        panelAsistencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Días de asistencia", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 14), java.awt.Color.black)); // NOI18N
        panelAsistencia.setAutoscrolls(true);
        panelAsistencia.setLayout(new java.awt.GridLayout(3, 10));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea1.setColumns(1);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(0);
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea1);

        panelAsistencia.add(jScrollPane3);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea2.setColumns(1);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setTabSize(0);
        jTextArea2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea2.setEnabled(false);
        jScrollPane4.setViewportView(jTextArea2);

        panelAsistencia.add(jScrollPane4);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea3.setColumns(1);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setTabSize(0);
        jTextArea3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea3.setEnabled(false);
        jScrollPane5.setViewportView(jTextArea3);

        panelAsistencia.add(jScrollPane5);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea4.setColumns(1);
        jTextArea4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setTabSize(0);
        jTextArea4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea4.setEnabled(false);
        jScrollPane6.setViewportView(jTextArea4);

        panelAsistencia.add(jScrollPane6);

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea5.setColumns(1);
        jTextArea5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setTabSize(0);
        jTextArea5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea5.setEnabled(false);
        jScrollPane7.setViewportView(jTextArea5);

        panelAsistencia.add(jScrollPane7);

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea6.setColumns(1);
        jTextArea6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(5);
        jTextArea6.setTabSize(0);
        jTextArea6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea6.setEnabled(false);
        jScrollPane8.setViewportView(jTextArea6);

        panelAsistencia.add(jScrollPane8);

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea7.setColumns(1);
        jTextArea7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea7.setLineWrap(true);
        jTextArea7.setRows(5);
        jTextArea7.setTabSize(0);
        jTextArea7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea7.setEnabled(false);
        jScrollPane9.setViewportView(jTextArea7);

        panelAsistencia.add(jScrollPane9);

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea8.setColumns(1);
        jTextArea8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea8.setLineWrap(true);
        jTextArea8.setRows(5);
        jTextArea8.setTabSize(0);
        jTextArea8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea8.setEnabled(false);
        jScrollPane10.setViewportView(jTextArea8);

        panelAsistencia.add(jScrollPane10);

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea9.setColumns(1);
        jTextArea9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea9.setLineWrap(true);
        jTextArea9.setRows(5);
        jTextArea9.setTabSize(0);
        jTextArea9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea9.setEnabled(false);
        jScrollPane11.setViewportView(jTextArea9);

        panelAsistencia.add(jScrollPane11);

        jTextArea10.setEditable(false);
        jTextArea10.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea10.setColumns(1);
        jTextArea10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea10.setLineWrap(true);
        jTextArea10.setRows(5);
        jTextArea10.setTabSize(0);
        jTextArea10.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea10.setEnabled(false);
        jScrollPane12.setViewportView(jTextArea10);

        panelAsistencia.add(jScrollPane12);

        jTextArea11.setEditable(false);
        jTextArea11.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea11.setColumns(1);
        jTextArea11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea11.setLineWrap(true);
        jTextArea11.setRows(5);
        jTextArea11.setTabSize(0);
        jTextArea11.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea11.setEnabled(false);
        jScrollPane13.setViewportView(jTextArea11);

        panelAsistencia.add(jScrollPane13);

        jTextArea12.setEditable(false);
        jTextArea12.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea12.setColumns(1);
        jTextArea12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea12.setLineWrap(true);
        jTextArea12.setRows(5);
        jTextArea12.setTabSize(0);
        jTextArea12.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea12.setEnabled(false);
        jScrollPane14.setViewportView(jTextArea12);

        panelAsistencia.add(jScrollPane14);

        jTextArea13.setEditable(false);
        jTextArea13.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea13.setColumns(1);
        jTextArea13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea13.setLineWrap(true);
        jTextArea13.setRows(5);
        jTextArea13.setTabSize(0);
        jTextArea13.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea13.setEnabled(false);
        jScrollPane15.setViewportView(jTextArea13);

        panelAsistencia.add(jScrollPane15);

        jTextArea14.setEditable(false);
        jTextArea14.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea14.setColumns(1);
        jTextArea14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea14.setLineWrap(true);
        jTextArea14.setRows(5);
        jTextArea14.setTabSize(0);
        jTextArea14.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea14.setEnabled(false);
        jScrollPane16.setViewportView(jTextArea14);

        panelAsistencia.add(jScrollPane16);

        jTextArea15.setEditable(false);
        jTextArea15.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea15.setColumns(1);
        jTextArea15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea15.setLineWrap(true);
        jTextArea15.setRows(5);
        jTextArea15.setTabSize(0);
        jTextArea15.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea15.setEnabled(false);
        jScrollPane17.setViewportView(jTextArea15);

        panelAsistencia.add(jScrollPane17);

        jTextArea16.setEditable(false);
        jTextArea16.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea16.setColumns(1);
        jTextArea16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea16.setLineWrap(true);
        jTextArea16.setRows(5);
        jTextArea16.setTabSize(0);
        jTextArea16.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea16.setEnabled(false);
        jScrollPane18.setViewportView(jTextArea16);

        panelAsistencia.add(jScrollPane18);

        jTextArea17.setEditable(false);
        jTextArea17.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea17.setColumns(1);
        jTextArea17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea17.setLineWrap(true);
        jTextArea17.setRows(5);
        jTextArea17.setTabSize(0);
        jTextArea17.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea17.setEnabled(false);
        jScrollPane19.setViewportView(jTextArea17);

        panelAsistencia.add(jScrollPane19);

        jTextArea18.setEditable(false);
        jTextArea18.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea18.setColumns(1);
        jTextArea18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea18.setLineWrap(true);
        jTextArea18.setRows(5);
        jTextArea18.setTabSize(0);
        jTextArea18.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea18.setEnabled(false);
        jScrollPane20.setViewportView(jTextArea18);

        panelAsistencia.add(jScrollPane20);

        jTextArea19.setEditable(false);
        jTextArea19.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea19.setColumns(1);
        jTextArea19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea19.setLineWrap(true);
        jTextArea19.setRows(5);
        jTextArea19.setTabSize(0);
        jTextArea19.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea19.setEnabled(false);
        jScrollPane21.setViewportView(jTextArea19);

        panelAsistencia.add(jScrollPane21);

        jTextArea20.setEditable(false);
        jTextArea20.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea20.setColumns(1);
        jTextArea20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea20.setLineWrap(true);
        jTextArea20.setRows(5);
        jTextArea20.setTabSize(0);
        jTextArea20.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea20.setEnabled(false);
        jScrollPane22.setViewportView(jTextArea20);

        panelAsistencia.add(jScrollPane22);

        jTextArea21.setEditable(false);
        jTextArea21.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea21.setColumns(1);
        jTextArea21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea21.setLineWrap(true);
        jTextArea21.setRows(5);
        jTextArea21.setTabSize(0);
        jTextArea21.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea21.setEnabled(false);
        jScrollPane23.setViewportView(jTextArea21);

        panelAsistencia.add(jScrollPane23);

        jTextArea22.setEditable(false);
        jTextArea22.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea22.setColumns(1);
        jTextArea22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea22.setLineWrap(true);
        jTextArea22.setRows(5);
        jTextArea22.setTabSize(0);
        jTextArea22.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea22.setEnabled(false);
        jScrollPane24.setViewportView(jTextArea22);

        panelAsistencia.add(jScrollPane24);

        jTextArea23.setEditable(false);
        jTextArea23.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea23.setColumns(1);
        jTextArea23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea23.setLineWrap(true);
        jTextArea23.setRows(5);
        jTextArea23.setTabSize(0);
        jTextArea23.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea23.setEnabled(false);
        jScrollPane25.setViewportView(jTextArea23);

        panelAsistencia.add(jScrollPane25);

        jTextArea24.setEditable(false);
        jTextArea24.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea24.setColumns(1);
        jTextArea24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea24.setLineWrap(true);
        jTextArea24.setRows(5);
        jTextArea24.setTabSize(0);
        jTextArea24.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea24.setEnabled(false);
        jScrollPane26.setViewportView(jTextArea24);

        panelAsistencia.add(jScrollPane26);

        jTextArea25.setEditable(false);
        jTextArea25.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea25.setColumns(1);
        jTextArea25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea25.setLineWrap(true);
        jTextArea25.setRows(5);
        jTextArea25.setTabSize(0);
        jTextArea25.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea25.setEnabled(false);
        jScrollPane27.setViewportView(jTextArea25);

        panelAsistencia.add(jScrollPane27);

        jTextArea26.setEditable(false);
        jTextArea26.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea26.setColumns(1);
        jTextArea26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea26.setLineWrap(true);
        jTextArea26.setRows(5);
        jTextArea26.setTabSize(0);
        jTextArea26.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea26.setEnabled(false);
        jScrollPane28.setViewportView(jTextArea26);

        panelAsistencia.add(jScrollPane28);

        jTextArea27.setEditable(false);
        jTextArea27.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea27.setColumns(1);
        jTextArea27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea27.setLineWrap(true);
        jTextArea27.setRows(5);
        jTextArea27.setTabSize(0);
        jTextArea27.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea27.setEnabled(false);
        jScrollPane29.setViewportView(jTextArea27);

        panelAsistencia.add(jScrollPane29);

        jTextArea28.setEditable(false);
        jTextArea28.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea28.setColumns(1);
        jTextArea28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea28.setLineWrap(true);
        jTextArea28.setRows(5);
        jTextArea28.setTabSize(0);
        jTextArea28.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea28.setEnabled(false);
        jScrollPane30.setViewportView(jTextArea28);

        panelAsistencia.add(jScrollPane30);

        jTextArea29.setEditable(false);
        jTextArea29.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea29.setColumns(1);
        jTextArea29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea29.setLineWrap(true);
        jTextArea29.setRows(5);
        jTextArea29.setTabSize(0);
        jTextArea29.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea29.setEnabled(false);
        jScrollPane31.setViewportView(jTextArea29);

        panelAsistencia.add(jScrollPane31);

        jTextArea30.setEditable(false);
        jTextArea30.setBackground(new java.awt.Color(236, 233, 216));
        jTextArea30.setColumns(1);
        jTextArea30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea30.setLineWrap(true);
        jTextArea30.setRows(5);
        jTextArea30.setTabSize(0);
        jTextArea30.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea30.setEnabled(false);
        jScrollPane32.setViewportView(jTextArea30);

        panelAsistencia.add(jScrollPane32);

        jPanel4.add(panelAsistencia, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivo");

        busquedaManual.setText("Busqueda manual");
        jMenu1.add(busquedaManual);

        limpiarVentana.setText("Limpiar ventana");
        jMenu1.add(limpiarVentana);

        darDeAlta.setText("Dar de alta");
        darDeAlta.setToolTipText("Dar de alta al socio inactivo y registrar pago");
        darDeAlta.setEnabled(false);
        jMenu1.add(darDeAlta);

        gestAsis.setText("Gestión asistencias");
        gestAsis.setEnabled(false);
        jMenu1.add(gestAsis);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(imHuella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {panelImage1, panelImage2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImage2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(imHuella, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new IngresoGui().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(IngresoGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }



    public JLabel getCantDias() {
        return cantDias;
    }

    public PanelImage getImHuella() {
        return imHuella;
    }

    public JLabel getFechaUltPago() {
        return fechaUltPago;
    }

    public JLabel getFechaVence() {
        return fechaVence;
    }

    public JLabel getNombre() {
        return nombre;
    }

    public JTextArea getTextoHuella() {
        return textoHuella;
    }

    public JMenuItem getDarDeAlta() {
        return darDeAlta;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem busquedaManual;
    private javax.swing.JLabel cantDias;
    private javax.swing.JMenuItem darDeAlta;
    private javax.swing.JLabel fechaUltPago;
    private javax.swing.JLabel fechaVence;
    private javax.swing.JMenuItem gestAsis;
    private org.edisoncor.gui.panel.PanelImage imHuella;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea25;
    private javax.swing.JTextArea jTextArea26;
    private javax.swing.JTextArea jTextArea27;
    private javax.swing.JTextArea jTextArea28;
    private javax.swing.JTextArea jTextArea29;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea30;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JMenuItem limpiarVentana;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel panelAsistencia;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private javax.swing.JTextArea textoHuella;
    // End of variables declaration//GEN-END:variables
}
