ALTER TABLE `gym`.`socios` 
CHANGE COLUMN `NOMBRE` `NOMBRE` VARCHAR(100) NULL DEFAULT NULL ,
CHANGE COLUMN `APELLIDO` `APELLIDO` VARCHAR(100) NULL DEFAULT NULL ,
CHANGE COLUMN `DNI` `DNI` VARCHAR(35) NULL DEFAULT NULL ,
CHANGE COLUMN `DIR` `DIR` VARCHAR(100) NULL DEFAULT NULL ,
CHANGE COLUMN `TEL` `TEL` VARCHAR(100) NULL DEFAULT NULL ,

ALTER TABLE `gym`.`arancels` 
CHANGE COLUMN `nombre` `nombre` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `gym`.`fichas` 
CHANGE COLUMN `TEL_EMERG` `TEL_EMERG` VARCHAR(100) NULL DEFAULT NULL ,
CHANGE COLUMN `ALERGICO` `ALERGICO` VARCHAR(100) NULL DEFAULT NULL ,
CHANGE COLUMN `MEDICAM` `MEDICAM` VARCHAR(100) NULL DEFAULT NULL ;
